name: Node Docker CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #debug added
      - name: Check files
        run: ls -al

      - name: Build Docker Image
        working-directory: personal_projects/node-docker-devops
        run: docker build -t tharangajw/node-devops-app:latest .

      - name: Push Docker Image
        run: docker push tharangajw/node-devops-app:latest